### PR TITLE
Fix performance of component configs

### LINKED ISSUE #2082: Performance issue: loading configuration of components
Loading a component configuration in a viewer with a _**large**_ layer tree takes ages (amplified when using oracle).

Cause:
appLayer.toJson()
---> addAttributes()

Only a small part of the components use the attributes (graph, simplefilter and cyclorama).

### PR DESCRIPTION
**Pull request by mtoonen**
- [x] Stop requesting attributes for all components
- [x] Fix Graph config
- [x] Fix simplefilter config
- [x] Fix cyclorama config

Fixes #2082

### CODE REVIEW

File: viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java [hunk 1]
```diff
@@ -213,12 +213,6 @@ public Resolution view() throws JSONException {
     public Resolution config() {
         EntityManager em = Stripersist.getEntityManager();
 
-        try {
-            appConfigJSON = application.toJSON(context.getRequest(),false,
-                    true, false, false,em, false).toString();
```
Comment (mprins) [inline viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java]: Why was it here? seems this is the only place it's used in this class and I can't find any other use... 
I think you could remove `appConfigJSON` from the class altogether

**Review by mprins — APPROVED** [review]
volgens mij kun je `appConfigJSON` uit de bean halen

File: viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java (hunk 1 above)
Comment (mtoonen) [reply viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java]: Done
