### PR TITLE
Fix publishing of a workversion of a mashup.

### LINKED ISSUE #851: Publish a workversion of mashup invalidates motherapplication
Have a motherapplication
One mashup (no workversion)
Create workversion of mashup
Publisch workversion and let all mashups point to the newly published application.

Now the motherapplication has an invalid startkaartbeeld.

### PR DESCRIPTION
**Pull request by mtoonen**
Fixes #851

### CODE REVIEW

File: viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBean.java [hunk 1]
```diff
@@ -413,23 +413,33 @@ public Resolution makeWorkVersion() {
...
+            Set<Application> apps = base.getRoot().findApplications(em);
+            for (Application app : apps) {
+                em.detach(app);
+            }
 
-        Set<Application> apps = base.getRoot().findApplications(em);
-        for (Application app : apps) {
-            em.detach(app);
+            em.persist(copy);
+            em.persist(copy);
```
Comment (mprins) [inline viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBean.java]: why do this `em.persist(copy);` twice?

File: viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBeanTest.java [hunk 2]
```diff
@@ -75,4 +76,44 @@ public void testCopyOfApplication(){
...
+            entityManager.getTransaction().begin();
+            entityManager.getTransaction().commit();
+            entityManager.getTransaction().begin();
+           
+            instance.setApplication(workVersion);
+            instance.publish(entityManager);
+            int a = 0;
+        } catch (Exception e) {
+            log.error("Fout", e);
+            assert (false);
```
Comment (mprins) [inline viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBeanTest.java:115]: If you use `fail ()` you can have the errormessage as part of the failure

File: viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java [hunk 3]
```diff
@@ -72,6 +75,101 @@ public void testMakeWorkVersionFromAppWithMashup() {
...
+            entityManager.getTransaction().commit();
+            entityManager.getTransaction().begin();   
+          
+            List origStartLayers = entityManager.createQuery("FROM StartLayer WHERE application = :app" , StartLayer.class).setParameter("app", app).getResultList();
+            List workversionStartLayers = entityManager.createQuery("FROM StartLayer WHERE application = :app" , StartLayer.class).setParameter("app", workVersion).getResultList();
+            assertEquals("Rootlevel should be the same ", app.getRoot().getId(),workVersion.getRoot().getId());
+            assertEquals(origStartLayers.size(), workversionStartLayers.size());
+        } catch (Exception e) {
+            log.error("Fout", e);
+            assert (false);
```
Comment (mprins) [inline viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java]: I would use `fail()` method

File: viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java [hunk 4]
```diff
@@ -72,6 +75,101 @@ public void testMakeWorkVersionFromAppWithMashup() {
...
+            List newAppStartLayers = entityManager.createQuery("FROM StartLayer WHERE application = :app" , StartLayer.class).setParameter("app", app).getResultList();
+            
+            assertEquals(origAppStartLayers.size(), newAppStartLayers.size());
+            
+            List workversionStartLayers = entityManager.createQuery("FROM StartLayer WHERE application = :app" , StartLayer.class).setParameter("app", workVersion).getResultList();
+            
+            assertEquals(app.getRoot().getId(),workVersion.getRoot().getId());
+        } catch (Exception e) {
+            log.error("Fout", e);
+            assert (false);
```
Comment (mprins) [inline viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java]: I would use `fail()` method

File: viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java [hunk 5]
```diff
@@ -72,6 +75,101 @@ public void testMakeWorkVersionFromAppWithMashup() {
...
+            ChooseApplicationActionBean caab = new ChooseApplicationActionBean();
+            TestActionBeanContext context = new TestActionBeanContext();
+            caab.setApplicationToDelete(app);
+            caab.setContext(context);
+             caab.deleteApplication(entityManager);
+            entityManager.getTransaction().begin();
+            entityManager.getTransaction().commit();
+        }catch(Exception e){
+            log.error("Fout", e);
+            assert (false);
```
Comment (mprins) [inline viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java]: I would use `fail()` method

**Review by mprins — APPROVED** [review]
Looking at the tests I think it should work as discussed. Some minor note on using  `fail()` method instead of `assert(false)`
